version: "2"
services:
  web:
    build: .
    labels:
      - "SERVICE_3000_NAME=github-bot-service"
      - "SERVICE_TAG=github-bot-serviceTag"
    restart: always
    # ports:
    # - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo